"""Run the three-arm ablation and the BKT fitting study.

    .venv/Scripts/python.exe scripts/run_ablation.py

Costs nothing: every arm is deterministic and runs against the local simulator, so the
whole study can be re-run in CI or on a plane.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from eval.ablation import Arm, render, run_ablation  # noqa: E402
from eval.bkt_fit import fit_and_report  # noqa: E402
from eval.retrieval_eval import evaluate, evaluate_by_kind  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser(description="CogniFlow ablation study")
    ap.add_argument("-n", type=int, default=80, help="cohort size per arm")
    ap.add_argument("--skip-bkt", action="store_true")
    ap.add_argument("--skip-retrieval", action="store_true")
    ap.add_argument("--out", type=Path, help="write results as JSON")
    args = ap.parse_args()
    logging.disable(logging.WARNING)

    print("=" * 78)
    print("ABLATION: does prerequisite-aware adaptation actually help?")
    print("=" * 78)
    print(f"Cohort: {args.n} simulated students per arm, identical across arms.")
    print("Half carry a PLANTED prerequisite gap; half are weak at the target with")
    print("prerequisites intact. The control half is what separates diagnosis from a")
    print("reflex -- a policy that always redirects would score well without it.")
    print()
    print("This measures the POLICY, not the model: no LLM is called in any arm. The")
    print("comparison that carries the result is A against B.")

    summaries = run_ablation(n=args.n)
    print(render(summaries))

    a = summaries[Arm.NO_PREREQ]
    b = summaries[Arm.RULES]
    print()
    print("READING THE RESULT")
    if b.median_steps and a.median_steps:
        delta = (a.median_steps - b.median_steps) / a.median_steps * 100
        print(f"  * Prerequisite-aware adaptation reached true mastery in "
              f"{b.median_steps:.0f} median attempts vs {a.median_steps:.0f} "
              f"({delta:.0f}% fewer).")
    print(f"  * It identified the planted gap in {b.gap_detection_rate*100:.0f}% of gapped "
          f"students. The no-prerequisite arm found it in {a.gap_detection_rate*100:.0f}% -- "
          "it cannot, by construction.")
    print(f"  * Its mastery estimates were roughly {a.mean_estimate_error/max(b.mean_estimate_error,1e-9):.1f}x "
          "closer to the students' true skill.")
    print(f"  * HONEST COST: it also redirected {b.false_redirect_rate*100:.0f}% of students "
          "who had no gap. Diagnosis is not free.")
    print()
    print("  Arm C is IDENTICAL to Arm B by construction, not by accident: this harness")
    print("  scores the POLICY, and both arms run the same deterministic policy. No")
    print("  model is called here at all, with or without an API key. C is reported as a")
    print("  separate row only to make that explicit rather than to imply a third result.")
    print()
    print("  The guard's effect on a model's proposals is real but is measured elsewhere,")
    print("  in a live session, where guard_override events are logged as they happen --")
    print("  see the event stream in `python run.py live`. It is not measured here, and")
    print("  this table should not be read as evidence about it.")

    payload = {
        arm.value: {
            "n": s.n,
            "mastery_rate": s.mastery_rate,
            "median_steps": s.median_steps,
            "gap_detection_rate": s.gap_detection_rate,
            "false_redirect_rate": s.false_redirect_rate,
            "mean_estimate_error": s.mean_estimate_error,
        }
        for arm, s in summaries.items()
    }

    if not args.skip_bkt:
        print()
        print("=" * 78)
        print("BKT PARAMETER FITTING")
        print("=" * 78)
        print("Trained on simulator trajectories, which are deliberately NOT generated by")
        print("a BKT process. Judged on held-out next-answer AUC. Adopted only on a")
        print("margin above 0.01.")
        print()
        reports = {}
        for skill in ("recursion", "functions", "loops"):
            report = fit_and_report(skill, n=300)
            print(report.line())
            reports[skill] = {
                "default_auc": report.default_auc,
                "fitted_auc": report.fitted_auc,
                "improvement": report.improvement,
                "adopted": report.adopt,
            }
        adopted = [s for s, r in reports.items() if r["adopted"]]
        print()
        if adopted:
            print(f"  Adopted fitted parameters for: {', '.join(adopted)}")
        else:
            print("  RESULT: fitting did NOT beat literature defaults by a meaningful")
            print("  margin. We ship the defaults. Reporting this rather than tuning")
            print("  until the number looks good is the point of having a held-out set.")
            print("  Note the defaults already reach ~0.85 AUC against a generative")
            print("  process BKT cannot represent, which is a result in itself.")
        payload["bkt_fitting"] = reports

    if not args.skip_retrieval:
        print()
        print("=" * 78)
        print("RETRIEVAL QUALITY")
        print("=" * 78)
        print("Ground-truth cases drawn from the two real consumers: remediation, and the")
        print("misconception diagnoser (queries are the diagnoser's own labels verbatim).")
        retrieval = evaluate()
        print(retrieval.render())
        print()
        for kind, res in evaluate_by_kind().items():
            print(f"  {kind:<14} recall@1 {res.recall_at_1 * 100:5.1f}%   "
                  f"recall@{res.k} {res.recall_at_k * 100:5.1f}%   MRR {res.mrr:.3f}")
        print()
        if retrieval.recall_at_k >= 1.0:
            print("  RESULT: the correct section reaches the model in EVERY case.")
            print("  A reranker would only reorder chunks that are already all present,")
            print("  so it was measured and deliberately NOT built. Same discipline as")
            print("  the BKT fitting result: measure first, and report a negative.")
        payload["retrieval"] = {
            "recall_at_1": retrieval.recall_at_1,
            "recall_at_k": retrieval.recall_at_k,
            "mrr": retrieval.mrr,
            "cases": retrieval.total,
        }

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        print(f"\nWrote {args.out}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
